name: Publish package to GitHub Packages
on:
  push:
    paths:
      - "backend/src/test-file-publish.txt"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_API_TOKEN_2 }}
