name: Publish package to GitHub Packages
on:
  push:
    paths:
      - "backend/src/test-file-publish.txt"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - run: git config user.email "andrew.e.dagdag@gmail.com"
      - run: git config user.name "Andrew-E-Dagdag
      - run: npm version patch
      - run: git push
      - run: npm ci
      - run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_API_TOKEN_2 }}
