# This is a basic workflow to help you get started with Actions

name: Deploy latest version to other repo

# Only trigger the workflow when there's a change in the specific file, for PE it should be the graphql file
on:
  push:
    paths:
      - "backend/src/test-file.txt"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run:  sh ./devspaces/build.sh
      - name: Push files
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # Set this as the `types.model.ts` file
          source_file: 'backend/src/models/graphql-generated/file.txt'
          destination_repo: 'Andrew-E-Dagdag/sample-receive-repository'
          destination_folder: 'path/to/build/in/frontend'
          user_email: 'andrew.e.dagdag@gmail.com'
          user_name: 'Andrew-E-Dagdag'
          # Highly recommend having a separate branch purely for sococo.graphql updates
          destination_branch: 'main'
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
