# This is a basic workflow to help you get started with Actions

name: Deploy latest version to other repo

# Only trigger the workflow when there's a change in the specific file, for PE it should be the graphql file
on:
  push:
    paths:
      - "backend/src/test-file.txt"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run:  sh ./devspaces/build.sh
      - name: Push files
#         uses: plocket/push-generated-file@master
#         with:
#           token: ${{ secrets.API_TOKEN_GITHUB }}
#           source_file_path: 'backend/src/models/graphql-generated'
#           # Should be the FE repo and file path
#           destination_repo: 'Andrew-E-Dagdag/sample-receive-repository'
#           destination_folder: 'path/to/build/in/frontend'
#           # You can choose to have a separate branch to push the new build files to
#           # and push those to main at your leisure, depends on FE
#           target_branch: 'main'
#           author: 'Andrew-E-Dagdag'
#           author_email: 'andrew.e.dagdag@gmail.com'
#               - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'backend/src/models/graphql-generated/file.txt'
          destination_repo: 'Andrew-E-Dagdag/sample-receive-repository'
          destination_folder: 'path/to/build/in/frontend'
          user_email: 'andrew.e.dagdag@gmail.com'
          user_name: 'Andrew-E-Dagdag'
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
